package wasmc:system-deferred-work@0.0.1;

interface deferred-work {
  enum class {
    refresh,
    processing,
  }

  record request {
    id: string,
    class: class,
    earliest-begin-wall-ms: u64,
  }

  schedule: func(request: request) -> result<_, s32>;
  pending: func() -> list<request>;
  cancel: func(id: string) -> result<_, s32>;
}

world system-deferred-work {
  export deferred-work;
}
