[package]
name = "wasmc-data-relational-component"
version = "0.0.2"
edition = "2024"
publish = false
license-file = "../../LICENSE"

[dependencies]
wasmtime = { version = "=49.0.0", default-features = false, features = ["runtime", "cranelift", "component-model"] }

[lib]
crate-type = ["rlib"]

[workspace]
