[package]
name = "wasmc-native-compiler"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[workspace]

[dependencies]
sha2 = "0.10"
wasmi = { version = "=2.0.0", default-features = false, features = ["std", "validate", "auto-dispatch"] }

[[bin]]
name = "wasmc-wasmi"
path = "src/main.rs"
