package wasmc:system-input@0.0.1;

interface input {
  tap: func(x: u32, y: u32) -> result<_, s32>;
  text: func(value: string) -> result<_, s32>;
  key-event: func(code: u32) -> result<_, s32>;
}

world system-input {
  export input;
}
