package wasmc:system-network-prototype@0.0.1;

record exchange-request {
  host: string,
  port: u16,
  payload: list<u8>,
}

interface network {
  exchange: func(request: exchange-request) -> result<list<u8>, string>;
}

world system-network-prototype {
  export network;
}
