[package]
name = "wasmc-tls-core-public"
version = "0.0.1"
edition = "2021"
publish = false
license-file = "../../LICENSE"
description = "Public clean-room WAsmC TLS Core Lib candidate"

[lib]
crate-type = ["cdylib"]

[dependencies]
wit-bindgen = "=0.62.0"
getrandom = { version = "=0.2.17", features = ["custom"] }
rustls = { version = "=0.23.44", default-features = false, features = ["custom-provider"] }
rustls-rustcrypto = { version = "=0.0.2-alpha", default-features = false, features = ["alloc"] }

[workspace]

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = "symbols"
