package wasmc:system-background-transfer@0.0.1;

interface background-transfer {
  enum state {
    pending,
    running,
    completed,
    failed,
    cancelled,
  }

  record transfer-info {
    id: u64,
    state: state,
    bytes-completed: u64,
    bytes-expected: u64,
    result-sha256: option<string>,
  }

  download: func(url: string) -> result<u64, s32>;
  inspect: func(id: u64) -> result<transfer-info, s32>;
  cancel: func(id: u64) -> result<_, s32>;
}

world system-background-transfer {
  export background-transfer;
}
