package wasmc:system-background-audio@0.0.1;

interface background-audio {
  enum state {
    stopped,
    playing,
    paused,
    interrupted,
    failed,
  }

  record snapshot {
    state: state,
    position-ms: u64,
    duration-ms: u64,
  }

  start: func() -> result<_, s32>;
  inspect: func() -> snapshot;
  stop: func() -> result<_, s32>;
}

world system-background-audio {
  export background-audio;
}
