package wasmc:system-linux-endpoint@0.0.1;

interface endpoints {
  record ready-event {
    events: u32,
    data: u64,
  }

  read-endpoint: func(path: string, maximum-bytes: u32) -> result<list<u8>, s32>;
  write-endpoint: func(path: string, payload: list<u8>) -> result<u64, s32>;

  resource mapping {
    read: func(offset: u64, maximum-bytes: u32) -> result<list<u8>, s32>;
    write: func(offset: u64, payload: list<u8>) -> result<u64, s32>;
    sync: func(linux-msync-flags: u32) -> result<_, s32>;
  }

  resource endpoint {
    read: func(maximum-bytes: u32) -> result<list<u8>, s32>;
    write: func(payload: list<u8>) -> result<u64, s32>;
    control: func(request: u64, argument: list<u8>, maximum-result-bytes: u32) -> result<tuple<s32, list<u8>>, s32>;
    poll: func(events: u16, timeout-milliseconds: s32) -> result<u16, s32>;
    map: func(offset: u64, length: u64, linux-protection: u32, linux-map-flags: u32) -> result<mapping, s32>;
  }

  resource event-set {
    control: func(linux-operation: s32, target: borrow<endpoint>, events: u32, data: u64) -> result<_, s32>;
    wait: func(maximum-events: u32, timeout-milliseconds: s32) -> result<list<ready-event>, s32>;
  }

  open-endpoint: func(path: string, linux-open-flags: u32) -> result<endpoint, s32>;
  create-event-set: func() -> result<event-set, s32>;
}

world system-linux-endpoint {
  export endpoints;
}
