package wasmc:system-linux-endpoint@0.0.1;

interface endpoints {
  read-endpoint: func(path: string, maximum-bytes: u32) -> result<list<u8>, s32>;
  write-endpoint: func(path: string, payload: list<u8>) -> result<u64, s32>;
}

world system-linux-endpoint {
  export endpoints;
}
