use crate::delta;
use crate::exports::wasmc::system_app_authorization::authorization as api;
pub struct Adapter;
fn capability_from(v:api::Capability)->delta::Capability{match v{api::Capability::Camera=>delta::Capability::Camera,api::Capability::Microphone=>delta::Capability::Microphone,api::Capability::LocationWhenInUse=>delta::Capability::LocationWhenInUse,api::Capability::Motion=>delta::Capability::Motion,api::Capability::Notifications=>delta::Capability::Notifications,api::Capability::PhotosReadWrite=>delta::Capability::PhotosReadWrite,api::Capability::Contacts=>delta::Capability::Contacts,api::Capability::Calendar=>delta::Capability::Calendar,api::Capability::Reminders=>delta::Capability::Reminders,api::Capability::SpeechRecognition=>delta::Capability::SpeechRecognition}}
fn capability_to(v:delta::Capability)->api::Capability{match v{delta::Capability::Camera=>api::Capability::Camera,delta::Capability::Microphone=>api::Capability::Microphone,delta::Capability::LocationWhenInUse=>api::Capability::LocationWhenInUse,delta::Capability::Motion=>api::Capability::Motion,delta::Capability::Notifications=>api::Capability::Notifications,delta::Capability::PhotosReadWrite=>api::Capability::PhotosReadWrite,delta::Capability::Contacts=>api::Capability::Contacts,delta::Capability::Calendar=>api::Capability::Calendar,delta::Capability::Reminders=>api::Capability::Reminders,delta::Capability::SpeechRecognition=>api::Capability::SpeechRecognition}}
fn state_from(v:api::State)->delta::State{match v{api::State::NotRequired=>delta::State::NotRequired,api::State::Unavailable=>delta::State::Unavailable,api::State::NotDetermined=>delta::State::NotDetermined,api::State::Denied=>delta::State::Denied,api::State::Restricted=>delta::State::Restricted,api::State::Authorized=>delta::State::Authorized,api::State::Limited=>delta::State::Limited,api::State::Provisional=>delta::State::Provisional,api::State::Ephemeral=>delta::State::Ephemeral,api::State::Unknown=>delta::State::Unknown}}
fn state_to(v:delta::State)->api::State{match v{delta::State::NotRequired=>api::State::NotRequired,delta::State::Unavailable=>api::State::Unavailable,delta::State::NotDetermined=>api::State::NotDetermined,delta::State::Denied=>api::State::Denied,delta::State::Restricted=>api::State::Restricted,delta::State::Authorized=>api::State::Authorized,delta::State::Limited=>api::State::Limited,delta::State::Provisional=>api::State::Provisional,delta::State::Ephemeral=>api::State::Ephemeral,delta::State::Unknown=>api::State::Unknown}}
fn plan_from(v:api::Plan)->delta::Plan{match v{api::Plan::NoRequest=>delta::Plan::NoRequest,api::Plan::Request=>delta::Plan::Request,api::Plan::WaitForInFlightRequest=>delta::Plan::WaitForInFlightRequest,api::Plan::OpenSettings=>delta::Plan::OpenSettings,api::Plan::FailClosed=>delta::Plan::FailClosed}}
fn plan_to(v:delta::Plan)->api::Plan{match v{delta::Plan::NoRequest=>api::Plan::NoRequest,delta::Plan::Request=>api::Plan::Request,delta::Plan::WaitForInFlightRequest=>api::Plan::WaitForInFlightRequest,delta::Plan::OpenSettings=>api::Plan::OpenSettings,delta::Plan::FailClosed=>api::Plan::FailClosed}}
fn decision(v:delta::Decision)->api::Decision{api::Decision{capability:capability_to(v.capability),state:state_to(v.state),attempt_count:v.attempt_count,request_in_flight:v.request_in_flight,plan:plan_to(v.plan)}}
impl api::Guest for Adapter{
 fn observe(c:api::Capability,s:api::State)->Result<(),i32>{delta::observe(capability_from(c),state_from(s))}
 fn snapshot()->Vec<api::Decision>{delta::snapshot().into_iter().map(decision).collect()}
 fn plan_request(c:Vec<api::Capability>)->Vec<api::Decision>{delta::plan_request(c.into_iter().map(capability_from).collect()).into_iter().map(decision).collect()}
 fn begin_request(c:api::Capability)->Result<u32,i32>{delta::begin_request(capability_from(c))}
 fn complete_request(c:api::Capability,id:u32,s:api::State)->Result<(),i32>{delta::complete_request(capability_from(c),id,state_from(s))}
}
