[package]
name = "wasmc-current-v2-consumer-qualification"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
wasmc-http1-component = { path = "../../../admission/current-v2-next/packages/wasmc-http1/0.0.1/bindings/rust" }
wasmc-host-clock-component = { path = "../../../admission/current-v2-next/packages/wasmc-host-clock/0.0.1/bindings/rust" }
wasmc-owned-algorithms-component = { path = "../../../admission/current-v2-next/packages/wasmc-owned-algorithms/0.1.0/bindings/rust" }
wasmc-resource-counter-component = { path = "../../../admission/current-v2-next/packages/wasmc-resource-counter/0.0.1/bindings/rust" }
wasmc-data-core-component = { path = "../../../admission/current-v2-data-core/packages/wasmc-data-core/0.0.1/bindings/rust" }

[workspace]
