[package]
name = "wasmc-http1-client-public"
version = "0.0.1"
edition = "2021"
publish = false
license-file = "../../LICENSE"
description = "Portable zero-import WAsmC HTTP/1.1 client wire Lib candidate"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wit-bindgen = "=0.62.0"
httparse = "=1.10.1"

[workspace]
