import fs from 'node:fs';
import assert from 'node:assert/strict';
import {instantiateLibSearch} from './client.mjs';
const root=new URL('../../standard/wasmc-lib-search/0.1.0/',import.meta.url);
const manifest=JSON.parse(fs.readFileSync(new URL('lib.json',root)));
const bytes=fs.readFileSync(new URL('artifact.wasm',root));
const pin={artifact_sha256:manifest.artifact.sha256,index_sha256:'c1ccd8f5086b3d3ae0643383f2d3e3e682358b4ccc4a99042233bd35fa73b534'};
const lib=instantiateLibSearch(bytes,pin);
const results=lib.search({text:'base64',include_historical:false},0,8);
assert.equal(results.ok.length,3);
assert.deepEqual(lib.lookup(results.ok[0].identity),results.ok[0]);
assert.deepEqual(lib.search({text:'',include_historical:false},0,65),{error:'invalid-limit'});
assert.deepEqual(lib.search({text:'a'.repeat(257),include_historical:false},0,1),{error:'invalid-query'});
assert.throws(()=>instantiateLibSearch(bytes,{...pin,artifact_sha256:'0'.repeat(64)}),/digest/);
assert.throws(()=>instantiateLibSearch(bytes,{...pin,index_sha256:'0'.repeat(64)}),/digest/);
assert.throws(()=>lib.search({text:'',include_historical:false},-1,1),/u32/);
console.log(JSON.stringify({accepted:true,snapshot:lib.snapshot(),hits:results.ok,client_checks:7}));
