import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import {resolve} from 'node:path';
import {checkedCurrentCatalog,verifyCurrentRelease,currentProductReader,currentProductPaths} from '../../scripts/current-lib-release-v3.mjs';
import {CurrentSearchCaller} from '../../scripts/current-lib-search-v3.mjs';
const root=fileURLToPath(new URL('../../',import.meta.url)),read=currentProductReader(root);
const bytes=read('catalog/libs-current-v2.json'),pin='a4de009c683d3db4453cf0a9e783719a933a8e1689842a12d08a6883a83cfdad';
const catalog=checkedCurrentCatalog(bytes,pin),closure=verifyCurrentRelease(bytes,pin,read,currentProductPaths(root));
const selected=catalog.packages.find(r=>r.id==='wasmc-lib-search');
const caller=new CurrentSearchCaller(read(catalog.index.path),read(selected.root+'/artifact.wasm'),read(selected.root+'/core-abi.json'));
const query={text:'base64',package_id:'wasmc-std',profile:null,bound_only:true};
const hits=caller.search(query,0,64);assert.equal(hits.tag,'ok');assert.ok(hits.value.length>=2);
for(let round=0;round<256;round++)for(const hit of hits.value)assert.deepEqual(caller.lookup(hit.identity),{tag:'ok',value:hit});
assert.deepEqual(caller.lookup('missing'),{tag:'ok',value:null});
assert.throws(()=>caller.search(query,0,65));assert.throws(()=>caller.search(query,-1,1));
const invalid=new CurrentSearchCaller(new TextEncoder().encode('{}'),read(selected.root+'/artifact.wasm'),read(selected.root+'/core-abi.json'));
assert.deepEqual(invalid.snapshot(),{tag:'err',value:'invalid-index'});
console.log(JSON.stringify({accepted:true,scope:'current compiled Core Search and exact complete Root/index identity',version:'0.5.0',snapshot:caller.snapshot(),closure,hits:hits.value,rounds:256,negative_cases:4,public_release_admission:false}));
